// Code generated by tygo. DO NOT EDIT.

//////////
// source: golf_course_client.go

/**
 * CourseSearchResponse is the top-level response from the API
 */
export interface SearchResponse {
  courses: APICourse[];
}
/**
 * APICourse is a single course from the API response
 */
export interface APICourse {
  id: number /* int */;
  club_name: string;
  course_name: string;
  location: APILocation;
  tees: APITees;
}
export interface APILocation {
  address: string;
  city: string;
  state: string;
  country: string;
}
export interface APITees {
  male: APITee[];
  female: APITee[];
}
export interface APITee {
  tee_name: string;
  course_rating: number /* float64 */;
  slope_rating: number /* int */;
  total_yards: number /* int */;
  par_total: number /* int */;
  holes: APIHole[];
}
export interface APIHole {
  par: number /* int */;
  yardage: number /* int */;
  handicap: number /* int */;
}
export interface GolfCourseClient {
}
