// Code generated by tygo. DO NOT EDIT.

//////////
// source: course.go

/**
 * Course is cached course identity and location data from the external Golf Course API.
 * It is intentionally separate from Tee because one course can have many playable tee sets.
 */
export interface Course {
  id: string;
  club_name: string;
  course_name: string;
  address: string;
  city: string;
  state: string;
  country: string;
  created_at: string;
}

//////////
// source: course_hole.go

/**
 * CourseHole is static hole metadata for a tee set.
 * This is different from Hole, which stores what the user scored during a specific round.
 */
export interface CourseHole {
  id: string;
  tee_id: string;
  hole_number: number /* int */;
  par: number /* int */;
  yardage: number /* int */;
  handicap: number /* int */;
}

//////////
// source: hole.go

/**
 * Hole is one hole scored within a round.
 * These are user-entered performance stats, so they are stored separately from static CourseHole data.
 */
export interface Hole {
  id: string;
  round_id: string;
  hole_number: number /* int */;
  score: number /* int */;
  fairway_hit: boolean;
  fairway_miss: string;
  gir: boolean;
  putts: number /* int */;
  green_miss: string;
  penalties: number /* int */;
}

//////////
// source: round.go

/**
 * Round is the parent record for one played round.
 * It references Tee instead of Course because score context depends on which tee set was played.
 */
export interface Round {
  id: string;
  tee_id: string;
  user_id: string;
  course_name: string;
  date: string;
  input_mode: string;
  created_at: string;
}

//////////
// source: tee.go

/**
 * Tee represents one playable tee set for a course.
 * Rating, slope, yardage, and par belong here because they change by tee, not just by course.
 */
export interface Tee {
  id: string;
  course_id: string;
  tee_name: string;
  course_rating: number /* float64 */;
  slope_rating: number /* int */;
  total_yards: number /* int */;
  par: number /* int */;
  created_at: string;
}
