// Code generated by tygo. DO NOT EDIT.

//////////
// source: course.go

export interface Course {
  id: string;
  club_name: string;
  course_name: string;
  address: string;
  city: string;
  state: string;
  country: string;
  created_at: string;
}

//////////
// source: course_hole.go

export interface CourseHole {
  id: string;
  tee_id: string;
  hole_number: number /* int */;
  par: number /* int */;
  yardage: number /* int */;
  handicap: number /* int */;
}

//////////
// source: hole.go

/**
 * Hole is one hole scored within a round.
 */
export interface Hole {
  id: string;
  round_id: string;
  hole_number: number /* int */;
  score: number /* int */;
  fairway_hit: boolean;
  gir: boolean;
  putts: number /* int */;
  miss_direction: string;
}

//////////
// source: round.go

/**
 * Round is a golf round aggregate.
 */
export interface Round {
  id: string;
  tee_id: string;
  user_id: string;
  date: string;
  input_mode: string;
  created_at: string;
}

//////////
// source: tee.go

export interface Tee {
  id: string;
  course_id: string;
  tee_name: string;
  course_rating: number /* float64 */;
  slope_rating: number /* int */;
  total_yards: number /* int */;
  par: number /* int */;
  created_at: string;
}
