package service

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/jccifuentes21/GolfTrackerCaddy/internal/golfDataApi"
	"github.com/jccifuentes21/GolfTrackerCaddy/internal/model"
	"github.com/jccifuentes21/GolfTrackerCaddy/internal/store"
)

// CourseService coordinates course workflows across the external API and three tables.
// This is business logic, so it lives above stores and below HTTP handlers.
type CourseService struct {
	courses     *store.CourseStore
	tees        *store.TeeStore
	courseHoles *store.CourseHoleStore
	apiClient   *golfDataApi.GolfCourseClient
}

// NewCourseService receives every dependency it needs.
// This makes the service easier to test because mocks or fakes can replace real stores later.
func NewCourseService(courses *store.CourseStore, tees *store.TeeStore, courseHoles *store.CourseHoleStore, apiClient *golfDataApi.GolfCourseClient) *CourseService {
	return &CourseService{
		courses:     courses,
		tees:        tees,
		courseHoles: courseHoles,
		apiClient:   apiClient,
	}
}

func (s *CourseService) SearchCourses(ctx context.Context, query string) (*golfDataApi.SearchResponse, error) {
	// For now search is a pass-through to the external API.
	// Keeping this method still helps preserve the handler-service-store layering.
	return s.apiClient.SearchCourses(ctx, query)
}

func (s *CourseService) SaveCourse(ctx context.Context, apiCourse *golfDataApi.APICourse) (*model.Course, []model.Tee, error) {
	// Translate external API data into the app's own domain model before saving.
	// That protects the database layer if the upstream API shape changes later.
	course := model.Course{
		ID:         fmt.Sprintf("%d", apiCourse.ID),
		ClubName:   apiCourse.ClubName,
		CourseName: apiCourse.CourseName,
		Address:    apiCourse.Location.Address,
		City:       apiCourse.Location.City,
		State:      apiCourse.Location.State,
		Country:    apiCourse.Location.Country,
	}

	if err := s.courses.Create(ctx, &course); err != nil {
		return nil, nil, fmt.Errorf("failed to save course: %w", err)
	}

	// The API separates male and female tees, but this app treats tee name as the identity
	// within a course so duplicate names do not create duplicate scorecard options.
	seen := make(map[string]bool)
	allTees := append(apiCourse.Tees.Male, apiCourse.Tees.Female...)

	var savedTees []model.Tee

	for _, apiTee := range allTees {
		if seen[apiTee.TeeName] {
			continue
		}
		seen[apiTee.TeeName] = true

		// UUIDs are generated by the application for locally-owned rows.
		// Course IDs come from the external API, but tees and course holes are our records.
		tee := model.Tee{
			ID:           uuid.New().String(),
			CourseID:     course.ID,
			TeeName:      apiTee.TeeName,
			CourseRating: apiTee.CourseRating,
			SlopeRating:  apiTee.SlopeRating,
			TotalYards:   apiTee.TotalYards,
			Par:          apiTee.ParTotal,
		}

		teeID, err := s.tees.Create(ctx, &tee)
		if err != nil {
			return nil, nil, fmt.Errorf("failed to save tee %s: %w", tee.TeeName, err)
		}
		tee.ID = teeID
		savedTees = append(savedTees, tee)

		// The external API gives holes as a slice, so the index becomes the 1-based hole number.
		var holes []model.CourseHole
		for i, apiHole := range apiTee.Holes {
			holes = append(holes, model.CourseHole{
				ID:         uuid.New().String(),
				TeeID:      teeID,
				HoleNumber: i + 1,
				Par:        apiHole.Par,
				Yardage:    apiHole.Yardage,
				Handicap:   apiHole.Handicap,
			})
		}
		if err := s.courseHoles.CreateBatch(ctx, holes); err != nil {
			return nil, nil, fmt.Errorf("failed to save course holes for tee %s: %w", tee.TeeName, err)
		}
	}
	return &course, savedTees, nil
}

// GetCourse is a thin read path for already-cached course data.
func (s *CourseService) GetCourse(ctx context.Context, courseID string) (*model.Course, error) {
	return s.courses.GetByID(ctx, courseID)
}

// GetTee is a thin read path for tee metadata such as par, rating, and slope.
func (s *CourseService) GetTee(ctx context.Context, teeID string) (*model.Tee, error) {
	return s.tees.GetByID(ctx, teeID)
}

func (s *CourseService) ListTeesByCourse(ctx context.Context, courseID string) ([]model.Tee, error) {
	return s.tees.ListByCourse(ctx, courseID)
}

func (s *CourseService) ListHolesByTee(ctx context.Context, teeID string) ([]model.CourseHole, error) {
	return s.courseHoles.ListByTee(ctx, teeID)
}
